### ISSUE TITLE
Telegram feed

### ISSUE THREAD

**Issue by lungdear** [OpenSDN-io/community#21]
Notification activity of OpenSDN to Telegram feed

**Comment by randybias** [comment]
A real time feed from Telegram group to Discord channel: tg-opensdn-feed

- Create a Discord bot in Python (use existing if possible)
- Tie it to telegram group
- One-way dump of all TG activity to this Discord channel
- Run it 24x7 on a server somewhere
- Make sure it restarts on crash

Ask @randybias if you need help with the Discord side.

**Comment by randybias** [comment]
This is done.
