### ISSUE TITLE
Transition Cassandra driver from Thrift to CQL

### ISSUE THREAD

**Issue by randybias** [OpenSDN-io/community#24]
Apologies, I didn't create an issue for this even though the work has already begun.  Please update this issue with latest.

**Comment by Andrey-mp** [comment]
switched to CQL here https://gerrit.opensdn.io/c/opensdn-io/tf-container-builder/+/518

now we'll work on removing pycassa/thrift modules from the codebase to be sure that we switched all places

**Comment by randybias** [comment]
It looks this is at least partially complete:

https://gerrit.opensdn.io/c/opensdn-io/tf-packages/+/608

But I see build failures. What's the status @Andrey-mp ?

**Comment by Andrey-mp** [comment]
this review is realated to removing pycassa/thrift from the build.
last issue with k8s setup only (we all forget to switch kube-manager component to cql also). it's simple. should be done in few days.

**Comment by Andrey-mp** [comment]
All reviews have been merged.
Thrift driver now is absent in the build
