### ISSUE TITLE
Support for Ubuntu 20.xx, Ubuntu 22.xx, and Rocky9

### ISSUE THREAD

**Issue by randybias** [OpenSDN-io/community#26]

**Comment by randybias** [comment]
@Andrey-mp status updates?

**Comment by Andrey-mp** [comment]
I think it can be closed now.

ubuntu 20.04 alreday worked well 

ubuntu 22.04 finished for ansible and juju deployers also:
- logs for successful job for juju http://nexus.gz1.opensdn.io:8082/jenkins_logs/nightly/pipeline_3/juju-os/
- logs for successful job for ansible http://nexus.gz1.opensdn.io:8082/jenkins_logs/nightly/pipeline_3/ansible-os-yoga/

deployment code adopted for rocky9 and all things deployed correctly. but issues after deploy with kenrel driver which is handled in another task https://github.com/OpenSDN-io/community/issues/8#issuecomment-2102089662
