### ISSUE TITLE
Send gerrit notifications to discord channel

### ISSUE THREAD

**Issue by randybias** [OpenSDN-io/community#3]
Send Gerrit review notifications and similar to discord channel.

**Comment by randybias** [comment]
@lungdear to push @tikitavi and @Andrey-mp to send all gerrit updates to a Discord channel.

**Comment by Andrey-mp** [comment]
It will be a huge spam channel. do we really need this?

**Comment by randybias** [comment]
Is there a subset of gerrit notifications that make sense?  Like reviews of PRs?

**Comment by Andrey-mp** [comment]
From my point of view - created and merged notifications only. So we will have codebase changes.

CI messages and user comments are huge flow and will hide useful messages.

**Comment by randybias** [comment]
Great.  Let's just do that then.

**Comment by randybias** [comment]
@Andrey-mp when do we get the Gerrit notifications in Discord?  We need a date you can commit to this.
