### ISSUE TITLE
Updated Contributor Instructions

### ISSUE THREAD

**Issue by randybias** [OpenSDN-io/community#30]
The instructions under:

http://docs.opensdn.io/contributing-to-opensdn/index.html

Are just not where they need to be.  Both inaccurate and have older LFN related processes.

**Comment by mkraposhin** [comment]
I made several revisions of the instruction: https://github.com/OpenSDN-io/docs/blob/master/contributing-to-opensdn/getting-started/getting-started-with-opensdn-development.rst 

However, my colleague found a place to correct, therefore I need one more turn of the document verification.

**Comment by randybias** [comment]
Any updates here?  How do we know when this is complete?

**Comment by Andrey-mp** [comment]
I think it can be closed - several people were able to contribute.
And we can fix any minor issues later if needed.
