### ISSUE TITLE
Tested / Supported Matrices for Release 24.1

### ISSUE THREAD

**Issue by randybias** [OpenSDN-io/community#46]
For the 24.1 release can we get a matrix of tested versions of OpenSDN 24.1 with OpenStack versions?  Similarly another matrix of OpenSDN 24.1 tested with specific Linux distros.

**Comment by Andrey-mp** [comment]
Current status:
Success:
- deploy openstack yoga version with ansible for ubuntu20 and ubuntu22
- deploy with ansible at ubuntu22 for openstack versions: wallaby, xena, yoga, zed, 2023.1, 2023.2
- deploy with ansible at ubuntu22 for openstack yoga with vanilla kolla-ansible
- deploy with juju at ubuntu22 for openstack yoga
- all unit tests

Fail:
- deploy openstack yoga with ansible at rocky9. Some problems in ansible - will check and fix soon.
- deploy with ansible at ubuntu22 for openstack ussuri and victoria. Issues with configuration of nova+libvirt. I suggest to skip this old releases or fix with low priority.
- deploy k8s wuth juju at ubuntu22 and pure manifests at rocky9 (kubespray way) - deploy is working but one of test is failing. Fix is in progress.

Will update with new results.

**Comment by randybias** [comment]
Let's put together a real matrix in Google Sheets or something similar?

**Comment by Andrey-mp** [comment]
I can't image how to create such matrix - it should have 3-5 dimensions %)

**Comment by Andrey-mp** [comment]
Updated success results:
- deploy openstack yoga with ansible at rocky9
- deploy k8s. With ansible - k8s v1.24.17, with juju - k8s v1.22.17, with pure manifests - k8s v1.28.6
