### ISSUE TITLE
Switch tf-ansible-deployer to newer versions of OpenStack

### ISSUE THREAD

**Issue by lungdear** [OpenSDN-io/community#6]
Switch tf-ansible-deployer to vanilla kolla-ansible for newer versions of OpenStack

**Comment by randybias** [comment]
We need @Andrey-mp to update this and provide more details.

**Comment by Andrey-mp** [comment]
deploy with patched kolla-ansible is ready for all versions up to wallaby.
from xena we have strnage behaviour for the cloud. sanity tests fail with "no valid host found" but manually I can create VM and it works.
So working on xena version and upper.

**Comment by randybias** [comment]
Any more updates @Andrey-mp ?

**Comment by Andrey-mp** [comment]
xena and yoga works well now.
zed and 2023.* don't work for me.
We decided that I'll wotk with @Yuri to clarify these issues cause he have working versions

**Comment by randybias** [comment]
Updates?  Do we have versions beyond Yoga working now?

**Comment by Andrey-mp** [comment]
We found what happens beyond yoga version and now woring on the fix. I hope it should be done next week.

**Comment by Andrey-mp** [comment]
zed, 2023.1, 2023.2 works now.
kolla-ansible dropped creation of admin endpoint for keystone. So we had to change it to public.
zed - https://gerrit.opensdn.io/c/opensdn-io/tf-jenkins/+/716
2023.1 - https://gerrit.opensdn.io/c/opensdn-io/tf-jenkins/+/743
2023.2 - https://gerrit.opensdn.io/c/opensdn-io/tf-jenkins/+/744
